#!/bin/bash
NAME=ideaIU-$1.tar.gz
TARGET_PATH=$2
PWD=$3
TYPE=$4
IDEA_URL=https://d1opms6zj7jotq.cloudfront.net/idea
WEB_STORM_URL=http://download-cf.jetbrains.com/webstorm


if [ $TYPE == "w" ]
then
  NAME=WebStorm-$1.tar.gz
fi


if [ -f $NAME ]
then
    echo "$NAME exists"
else
  if [ $TYPE == "w" ]
  then
    wget $WEB_STORM_URL/$NAME
  else
    wget $IDEA_URL/$NAME
  fi
fi




echo -e $PWD | sudo -S rm -r $TARGET_PATH
echo -e $PWD | sudo -S mkdir -p $TARGET_PATH
echo -e $PWD | sudo -S chown `whoami` $TARGET_PATH
tar -xzf $NAME --strip=1 -C $TARGET_PATH
rm $NAME

